# Generated by Django 4.2.11 on 2024-04-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woodmenu',
            name='slug',
            field=models.SlugField(auto_created=True, unique=True),
        ),
    ]
